import { readFile, access } from 'node:fs/promises';
import { constants } from 'node:fs';

const requiredFiles = [
  'apps/web/index.html',
  'apps/web/react-app.css',
  'apps/web/taskzen-theme.css',
  'apps/web/taskzen-responsive.css',
  'apps/web/taskzen-shell.js',
  'apps/web/app.js',
  'apps/web/engine.js',
  'apps/web/workspace-store.js',
  'apps/web/analysis-client.js',
  'apps/web/critic-core.js',
  'apps/web/browser-critic-runtime.js',
  'apps/web/critic-client.js',
  'apps/web/critic-console.js',
  'apps/web/critic-console.css',
  'apps/web/result-contract.js',
  'apps/web/temporary-worker-contract.js',
  'apps/web/manifest.webmanifest',
  'apps/web/favicon.svg',
  'apps/web/.nojekyll',
  'services/gateway/app.mjs',
  'services/gateway/config.mjs',
  'services/gateway/errors.mjs',
  'services/gateway/provider-registry.mjs',
  'services/gateway/temporary-critic.mjs',
  'services/gateway/providers/architecture-guidance.mjs',
  'services/gateway/providers/deterministic.mjs',
  'services/gateway/providers/ollama.mjs',
  'services/gateway/providers/openrouter.mjs',
  'services/gateway/providers/provider-http.mjs',
  'services/gateway/server.mjs',
  'services/gateway/Dockerfile',
  'scripts/capture-ui-viewport.mjs',
  'scripts/verify-live-browser-critic.mjs',
  'scripts/validate-taskzen.mjs',
  'docs/architecture/ANALYSIS_GATEWAY.md',
  'docs/architecture/NO_BUILD_REACT.md',
  'docs/architecture/TEMPORARY_CRITIC.md',
  'docs/architecture/FRAMER_TASKZEN_VISUAL_SYSTEM.md',
  '.github/workflows/application-ci.yml',
  '.github/workflows/deploy-pages.yml',
  '.github/workflows/verify-pages.yml',
  '.github/workflows/ui-viewport-audit.yml'
];

for (const path of requiredFiles) await access(path, constants.R_OK);

const read = (path) => readFile(path, 'utf8');
const [
  html,
  app,
  baseCss,
  taskzenTheme,
  taskzenResponsive,
  taskzenShell,
  engine,
  workspace,
  analysisClient,
  criticCore,
  browserCritic,
  criticClient,
  criticConsole,
  criticCss,
  resultContract,
  workerContract,
  gateway,
  gatewayConfig,
  gatewayErrors,
  registry,
  gatewayCritic,
  guidance,
  deterministic,
  providerHttp,
  ollama,
  openrouter,
  dockerfile,
  captureViewport,
  liveCriticVerifier,
  deploy,
  verifyPages,
  viewportAudit
] = await Promise.all([
  read('apps/web/index.html'),
  read('apps/web/app.js'),
  read('apps/web/react-app.css'),
  read('apps/web/taskzen-theme.css'),
  read('apps/web/taskzen-responsive.css'),
  read('apps/web/taskzen-shell.js'),
  read('apps/web/engine.js'),
  read('apps/web/workspace-store.js'),
  read('apps/web/analysis-client.js'),
  read('apps/web/critic-core.js'),
  read('apps/web/browser-critic-runtime.js'),
  read('apps/web/critic-client.js'),
  read('apps/web/critic-console.js'),
  read('apps/web/critic-console.css'),
  read('apps/web/result-contract.js'),
  read('apps/web/temporary-worker-contract.js'),
  read('services/gateway/app.mjs'),
  read('services/gateway/config.mjs'),
  read('services/gateway/errors.mjs'),
  read('services/gateway/provider-registry.mjs'),
  read('services/gateway/temporary-critic.mjs'),
  read('services/gateway/providers/architecture-guidance.mjs'),
  read('services/gateway/providers/deterministic.mjs'),
  read('services/gateway/providers/provider-http.mjs'),
  read('services/gateway/providers/ollama.mjs'),
  read('services/gateway/providers/openrouter.mjs'),
  read('services/gateway/Dockerfile'),
  read('scripts/capture-ui-viewport.mjs'),
  read('scripts/verify-live-browser-critic.mjs'),
  read('.github/workflows/deploy-pages.yml'),
  read('.github/workflows/verify-pages.yml'),
  read('.github/workflows/ui-viewport-audit.yml')
]);

const checks = [
  [html.includes('id="root"'), 'index must provide the React mount root'],
  [html.includes('href="./react-app.css"'), 'index must load the functional stylesheet'],
  [html.includes('href="./taskzen-theme.css"'), 'index must load the Taskzen visual system'],
  [html.includes('href="./taskzen-responsive.css"'), 'index must load responsive refinements'],
  [!html.includes('neuronest-theme.css'), 'superseded theme must remain absent'],
  [html.includes('type="module" src="./taskzen-shell.js"'), 'index must load the responsive shell'],
  [html.includes('type="module" src="./critic-console.js"'), 'index must load the critic console'],
  [html.includes('type="module" src="./app.js"'), 'index must load the React app'],
  [html.indexOf('src="./taskzen-shell.js"') < html.indexOf('src="./critic-console.js"'), 'responsive shell must initialize before critic console'],
  [html.indexOf('src="./critic-console.js"') < html.indexOf('src="./app.js"'), 'critic console must subscribe before the app emits its initial result'],
  [html.includes('react@18.3.1/umd/react.production.min.js'), 'React runtime must be pinned'],
  [html.includes('react-dom@18.3.1/umd/react-dom.production.min.js'), 'ReactDOM runtime must be pinned'],
  [html.includes('htm@3.1.1/dist/htm.umd.js'), 'HTM runtime must be pinned'],
  [!html.includes('text/babel'), 'the deployed application must remain build-free'],
  [!html.includes('type="password"'), 'the static application must not collect provider credentials'],

  [app.includes('HtmRuntime.bind(ReactRuntime.createElement)'), 'app must render without JSX compilation'],
  [app.includes('ReactDomRuntime.createRoot(rootElement)'), 'app must mount through ReactDOM'],
  [app.includes("from './engine.js'"), 'app must preserve deterministic planning'],
  [app.includes("from './analysis-client.js'"), 'app must preserve provider-neutral analysis'],
  [app.includes("from './workspace-store.js'"), 'app must preserve replaceable workspace storage'],
  [app.includes('planned, not executed'), 'general planned subagents must remain disclosed as not executed'],
  [app.includes('No provider keys in browser'), 'browser credential boundary must remain visible'],

  [baseCss.includes('.architecture-map'), 'functional CSS must include the architecture map'],
  [baseCss.includes('.agent-card-grid'), 'functional CSS must include temporary-agent cards'],
  [baseCss.includes('.permission-table'), 'functional CSS must include the permission matrix'],
  [baseCss.includes('.trace-timeline'), 'functional CSS must include the trace timeline'],
  [taskzenTheme.includes('--cyan: #635bff'), 'Taskzen theme must define the indigo accent'],
  [taskzenTheme.includes('--teal: #0e9384'), 'Taskzen theme must define the teal accent'],
  [taskzenResponsive.includes('.result-tabs'), 'responsive layer must protect phone result navigation'],
  [taskzenShell.includes("const DESIGN_ID = 'taskzen'"), 'responsive shell must identify the active design'],
  [taskzenShell.includes('setInert(sidebar, true)'), 'closed responsive navigation must become inert'],
  [taskzenShell.includes("sidebar.setAttribute('aria-hidden', 'true')"), 'closed responsive navigation must leave the accessibility tree'],

  [criticCore.includes('MAX_CRITIC_CONTEXT_BYTES = 48 * 1024'), 'portable critic core must bound context'],
  [criticCore.includes('tools: []'), 'portable critic core must expose no tools'],
  [criticCore.includes('externalActions: false'), 'portable critic core must deny external actions'],
  [criticCore.includes('childSpawning: false'), 'portable critic core must deny child workers'],
  [criticCore.includes('modelCallBudget: 1'), 'portable critic core must enforce one bounded invocation'],
  [criticCore.includes('Temporary critic findings cannot weaken permissions'), 'portable critic core must preserve authoritative controls'],
  [!criticCore.includes("from 'node:"), 'portable critic core must remain browser-compatible'],
  [!criticCore.includes('fetch('), 'portable critic core must not perform network access'],

  [browserCritic.includes('executeBrowserDeterministicCritic'), 'browser runtime must expose deterministic execution'],
  [browserCritic.includes("execution: 'browser-local'"), 'browser runtime must record its execution path'],
  [browserCritic.includes('networkRequests: 0'), 'browser runtime must record zero network requests'],
  [browserCritic.includes("provider: 'deterministic'"), 'browser runtime must retain deterministic provenance'],
  [!browserCritic.includes('fetch('), 'browser runtime must not perform network access'],
  [!browserCritic.includes('OPENROUTER_API_KEY'), 'browser runtime must not reference provider credentials'],

  [criticClient.includes('executeBrowserDeterministicCritic'), 'critic client must route browser mode locally'],
  [criticClient.includes('settings.mode === RuntimeModes.BROWSER'), 'critic client must distinguish browser mode'],
  [criticClient.includes("'/v1/critique'") || criticClient.includes('/v1/critique'), 'critic client must retain the bounded gateway endpoint'],
  [criticClient.includes('JSON.stringify({ result })'), 'gateway critic request must send only the harness result'],
  [!criticClient.toLowerCase().includes('authorization:'), 'critic client must not construct provider authorization'],
  [criticConsole.includes('Browser local · no network'), 'critic console must expose browser-local execution'],
  [criticConsole.includes('One local invocation'), 'critic console must disclose local call limits'],
  [criticConsole.includes('One provider call'), 'critic console must disclose gateway call limits'],
  [criticConsole.includes('No tools') && criticConsole.includes('No child agents') && criticConsole.includes('No external actions'), 'critic console must disclose non-capabilities'],
  [criticCss.includes('.critic-drawer') && criticCss.includes('.finding-card'), 'critic console visuals must remain available'],
  [criticCss.includes('@media (max-width: 760px)'), 'critic console must remain responsive'],
  [criticCss.includes('prefers-reduced-motion'), 'critic console must respect reduced motion'],

  [resultContract.includes('validateHarnessResult'), 'shared result validation is required'],
  [workerContract.includes('validateTemporaryWorker'), 'shared worker validation is required'],
  [workerContract.includes('callBudget must equal 1'), 'worker must retain one-call budget'],
  [workerContract.includes('tools must be an empty array'), 'worker contract must deny tools'],
  [workerContract.includes('childSpawning must be false'), 'worker contract must deny child spawning'],
  [workerContract.includes('externalActions must be false'), 'worker contract must deny external actions'],
  [workspace.includes('WORKSPACE_SCHEMA_VERSION'), 'workspace persistence must remain versioned'],
  [workspace.includes('MAX_RUNS_PER_PROJECT'), 'workspace retention must remain bounded'],
  [engine.includes('no live model or external tool execution'), 'deterministic planner must disclose its boundary'],

  [gatewayCritic.includes("from '../../apps/web/critic-core.js'"), 'gateway critic must share the portable core'],
  [gatewayCritic.includes("createHash('sha256')"), 'gateway critic must derive the same SHA-256 context identifier'],
  [gateway.includes("'/health'") && gateway.includes("'/v1/analyze'") && gateway.includes("'/v1/critique'"), 'gateway routes must remain available'],
  [gateway.includes('maxTemporaryWorkersPerRequest: 1'), 'gateway must expose the one-worker limit'],
  [gateway.includes('executeTools: false') && gateway.includes('externalActions: false'), 'gateway must deny execution capabilities'],
  [gateway.includes('ORIGIN_NOT_ALLOWED'), 'gateway must retain exact-origin CORS enforcement'],
  [gatewayConfig.includes("'deterministic'") && gatewayConfig.includes("'openrouter'"), 'gateway must retain deterministic and OpenRouter providers'],
  [gatewayConfig.includes('normalizeFreeOpenRouterModel'), 'gateway must enforce free-only OpenRouter routes'],
  [gatewayErrors.includes('ProviderResponseError'), 'gateway must retain provider response errors'],
  [registry.includes('createOpenRouterProvider'), 'provider registry must retain OpenRouter'],
  [guidance.includes('deterministic HarnessLab controls remain authoritative'), 'model guidance must remain advisory'],
  [deterministic.includes('async critique'), 'deterministic gateway provider must support critique'],
  [providerHttp.includes('await response.text()'), 'provider timeout must include response bodies'],
  [ollama.includes('createCriticPrompt') && ollama.includes('parseCriticReview'), 'Ollama must retain bounded critic parsing'],
  [openrouter.includes('https://openrouter.ai/api/v1'), 'OpenRouter must use the fixed official origin'],
  [openrouter.includes('openrouter/free') && openrouter.includes("endsWith(':free')"), 'OpenRouter must remain free-only'],
  [openrouter.includes('createCriticPrompt') && openrouter.includes('parseCriticReview'), 'OpenRouter must retain bounded critic parsing'],
  [dockerfile.includes('USER node'), 'gateway container must run non-root'],

  [captureViewport.includes('Emulation.setDeviceMetricsOverride'), 'viewport QA must use exact browser emulation'],
  [captureViewport.includes('Page.captureScreenshot'), 'viewport QA must retain screenshots'],
  [liveCriticVerifier.includes('Browser-local critic execution'), 'live verifier must execute the public browser critic'],
  [liveCriticVerifier.includes('prohibitedRequests.length === 0'), 'live verifier must reject critic network calls'],
  [viewportAudit.includes('audit_viewport desktop 1440 1100'), 'desktop QA is required'],
  [viewportAudit.includes('audit_viewport tablet 1024 900'), 'tablet QA is required'],
  [viewportAudit.includes('audit_viewport phone 390 844'), 'phone QA is required'],
  [deploy.includes('actions/deploy-pages@'), 'deployment must use the official Pages action'],
  [deploy.includes('path: apps/web'), 'deployment must publish only the web directory'],
  [verifyPages.includes('/critic-console.js'), 'live verification must check the critic console'],
  [verifyPages.includes('/temporary-worker-contract.js'), 'live verification must check the worker contract']
];

for (const [condition, message] of checks) {
  if (!condition) throw new Error(message);
}

const browserBundle = [
  html,
  app,
  engine,
  workspace,
  analysisClient,
  criticCore,
  browserCritic,
  criticClient,
  criticConsole,
  resultContract,
  workerContract
].join('\n');

const forbiddenPatterns = [
  /sk-[A-Za-z0-9_-]{20,}/,
  /BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY/,
  /Bearer\s+[A-Za-z0-9._-]{20,}/i
];

for (const [name, content] of [
  ['browser-bundle', browserBundle],
  ['gateway', gateway],
  ['gateway-config', gatewayConfig],
  ['registry', registry],
  ['gateway-critic', gatewayCritic],
  ['guidance', guidance],
  ['provider-http', providerHttp],
  ['ollama', ollama],
  ['openrouter', openrouter],
  ['dockerfile', dockerfile],
  ['deploy', deploy],
  ['verify-pages', verifyPages]
]) {
  for (const pattern of forbiddenPatterns) {
    if (pattern.test(content)) throw new Error(`Potential secret found in ${name}`);
  }
}

console.log(`Validated ${requiredFiles.length} no-build React, local critic, gateway, worker, UI, and deployment files.`);
